Hw2
sejapoe/tinkoff-ab-sem2-dz1 pull request #1
Opened 2024-02-25 16:47 UTC by sejapoe

2024-03-03 18:33 UTC, MaximKozlyuk approved these changes

2024-03-25 07:44 UTC, MaximKozlyuk requested changes

2024-03-25 07:44 UTC, MaximKozlyuk commented on src/main/java/ru/sejapoe/dz1/controller/StorageController.java
> +                .filter(f -> f.contains("."))
А если filename без точки? Такие тоже бывают)

2024-03-25 07:44 UTC, MaximKozlyuk commented on src/main/java/ru/sejapoe/dz1/controller/StorageController.java
> +                .map(f -> f.substring(filename.lastIndexOf(".") + 1));
fyi В работе с путями можно такие штуки пользовать

https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FilenameUtils.html#getExtension(java.lang.String)

2024-03-25 07:44 UTC, MaximKozlyuk commented on src/main/java/ru/sejapoe/dz1/controller/StorageController.java
> +        MediaType mediaType = MediaType.parseMediaType("image/" + ext.get());
Тут потенциальное NPE

2024-03-25 07:44 UTC, MaximKozlyuk commented on src/main/java/ru/sejapoe/dz1/model/Operation.java
> +import jakarta.persistence.Id;
minor: unused imports

https://www.jetbrains.com/guide/java/tips/optimize-imports/#:~:text=Remove%20unused%20imports%20from%20your%20code&text=Optimize%20Imports%20using%20the%20shortcut,Optimize%20imports%20on%20the%20fly.

2024-03-25 07:44 UTC, MaximKozlyuk commented on compose.yaml
> +  redis:
в конфигах прикрутил а в коде не увидел как используется redis. Подскажи плз где используешь

2024-03-25 07:44 UTC, MaximKozlyuk commented on src/main/java/ru/sejapoe/dz1/storage/StorageService.java
> +    void deleteAll();
Достаточно рисковая операция и сомнительно что нужная)
Лучше добавь к следующему разу просто delete by имя / id

2024-03-25 17:54 UTC, sejapoe commented on src/main/java/ru/sejapoe/dz1/controller/StorageController.java
> +                .filter(f -> f.contains("."))
Для этого и использую Optional, тогда он станет пустым и в итоге не пройдет дальнейшую проверку

2024-03-25 17:54 UTC, sejapoe commented on src/main/java/ru/sejapoe/dz1/controller/StorageController.java
> +                .map(f -> f.substring(filename.lastIndexOf(".") + 1));
Да, так действительно проще)

2024-03-25 17:55 UTC, sejapoe commented on src/main/java/ru/sejapoe/dz1/controller/StorageController.java
> +        MediaType mediaType = MediaType.parseMediaType("image/" + ext.get());
На ext.get()? Вроде не должно быть, есть провека на ext.isEmpty()

2024-03-25 17:56 UTC, sejapoe commented on src/main/java/ru/sejapoe/dz1/storage/StorageService.java
> +    void deleteAll();
Согласен, поменял в версии для проекта

2024-04-01 09:38 UTC, MaximKozlyuk approved these changes

2024-04-12 16:26 UTC, merged